export const ABOUT = '/ ';
export const REGISTER = '/register';
export const SIGN_IN = '/signin';
export const ACCOUNT = '/account';
export const PW_FORGET = '/pw-forget';
export const PW_RESET = '/pw-reset';
export const HCP_EDIT = '/hcp-edit';
export const MATCHES = '/matches';
export const MATCH = '/matches/:id';